### ISSUE TITLE
redir doesn't start

### ISSUE THREAD

**Issue by stiv-yakovenko** [troglobit/redir#13]
Built redir, but it doesn't start:

![image](https://user-images.githubusercontent.com/4163254/57965067-4f459d00-7969-11e9-8448-89674c00cce9.png)

**Comment by troglobit** [comment]
Just tested the latest master, which is same as v3.3, and it works here.  Both foreground and in the background like you run.

You'll have to tell me a bit more about your setup, the version of redir you're using etc.

**Comment by stiv-yakovenko** [comment]
Thank you for your feedback. I use Centos 7, built from lastest git sources. Any particular details?

**Comment by troglobit** [comment]
Well, how did you run the configure script; args, any special environment perhaps, the output from the configure script and the config.log file would be a start.   I'll see if I can fire up a CentOS machine later today.

**Comment by troglobit** [comment]
I just hit me, do you have any SELinux, Apparmor or other policy/access control mechanism enabled?  You can usually see the kernel denying application access in the dmesg or other kernel log file, dunno how/what CentOS/RedHat does here.

**Comment by stiv-yakovenko** [comment]
well, may be, but i'd expect error message if it fails to listen?

**Comment by stiv-yakovenko** [comment]
I can give you ssh for debugging purposes if you wish

**Comment by troglobit** [comment]
Have you tried running it in the foreground with debug messages enabled?

    ./redir -n -l debug 0.0.0.0:2222 127.0.0.0:2222

I agree, there should be an error message, could be the wrong log level is set, but `-l debug` should catch that.

Let's keep ssh login as a backup.

**Comment by stiv-yakovenko** [comment]
HI! Will check today's evening, busy right now.

**Comment by stiv-yakovenko** [comment]
ok, -n gives error message, but in bg mode it doesn't, which is a bit missleading in my opinion.

**Comment by troglobit** [comment]
Could you please tell me what the error message is?  When redir runs in the background it cannot log to the terminal it starts from, only to syslog like other daemons. Maybe the error message is available in /var/log/syslog?

**Comment by stiv-yakovenko** [comment]
Well, it said port was busy. I think may be its not a bug at all...

**Comment by troglobit** [comment]
You can check open/used ports with netstat or ss. Maybe you already have an application listening to 2222?

**Comment by stiv-yakovenko** [comment]
yeah, the problem itself is solved, but no message was a bit missleading :)

**Comment by troglobit** [comment]
Like I said, when redir runs in the background (default) it has detached from the terminal (to protect itself from being killed if you close your terminal), so it cannot give you any feedback other than in the syslog.  This goes for *all* UNIX daemons. I understand that can be a bit confusing, but I have not tried to mislead you our any other user in any way.  I just want to make this clear.

OK so we can close this issue then?

**Comment by stiv-yakovenko** [comment]
yes, close it
