### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by ozican** [troglobit/redir#21]
Hello, I try with full new installed Ubuntu 20 TLS but still no luck.
I get that error;
Failed connecting to target 127.0.0.1: Connection refused

I tried them;
redir :1019 127.0.0.1:80
redir --lport=1019 --caddr=127.0.0.1
redir --lport=1019 --caddr=127.0.0.1 --cport=80
redir --lport=1019 --caddr=127.0.0.1 --cport=8080

I don't understand. Why should be? 

By the way I am trying to connect from my local macOS with Firefox proxy settings: 192.168.0.19 Port: 1019

**Comment by troglobit** [comment]
What version of redir are you using? If you're using a packaged version from Ubuntub you should report it to them first. They handle communications from there on with this project. If not, and you're building redir yourself, then please tell me how you've run configure and make.

**Comment by troglobit** [comment]
Some information on what you're trying to achieve of of course also very helpful. Not all things can be done with redir ...

**Comment by ozican** [comment]
I use redir v3.2 and I installed via apt get install command.

My achive is directing the ppp0 interface.

**Comment by troglobit** [comment]
Like I said, Ubuntu is first line support for software they package and distribute, so you should contact them first.

However, I just tested redir in Linux Mint (which I run), and it works just fine:

 1. First I start my web server on port 8080, it listens to 127.0.0.1:8080
 2. Then I start redir like this: `sudo redir -n :80 127.0.0.1:8080`
 3. Connecting to 127.0.0.1 using curl or Firefox then redirects, behind the scenes using redir, to 127.0.0.1:8080

I don't know why it doesn't work for you, but I cannot help you troubleshoot that.
