### ISSUE TITLE
delete rules

### ISSUE THREAD

**Issue by uqlel** [troglobit/redir#23]
how to delete port forwarding rules?

**Comment by troglobit** [comment]
What do you mean, what are you trying to do, specifically?

**Comment by uqlel** [comment]
I mean I entered the wrong port for redirection and I want to remove it to make that port work normally

**Comment by troglobit** [comment]
Just stop the `redir` process.  It's nothing more than that, but I don't know how redir is integrated in your system or how you start it.  You can check with both the ps command and netstat what processes are running or ports are open/redirected.
