### ISSUE TITLE
Hello how to use install-sh？

### ISSUE THREAD

**Issue by zy8270** [troglobit/redir#29]
How to install redir in centos7

**Comment by zy8270** [comment]
[root@csfrnlyqfeaooq redir-3.3]# ./install-sh -g ./configure ./aa
./install-sh: no input file specified.
[root@csfrnlyqfeaooq redir-3.3]#

**Comment by kangxiaojia0** [comment]
Can point code in detail

**Comment by kangxiaojia0** [comment]
Can you be more detailed?

**Comment by kangxiaojia0** [comment]
thanks
