### ISSUE TITLE
There is a problem using this software for port forwarding and v2ray together

### ISSUE THREAD

**Issue by avawuw** [troglobit/redir#33]
I am using the software on debian and I have forwarded to multiple ports, but when I use the v2ray server at the same time, I find that the local side informs me that there is a problem with the proxy server, all my firewalls have been turned off and the v2ray run logs do not report any errors, I would like to ask what I need to do to use this software together with v2ray
Thank you

**Comment by troglobit** [comment]
I don't know how v2ray works, so impossible to answer.  redir is only a simple port forwarder.
